name = "learning-lean"
version = "0.1.0"
defaultTargets = ["LearningLean", "learning-lean"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.26.0"

[[lean_lib]]
name = "LearningLean"

[[lean_exe]]
name = "learning-lean"
root = "Main"
